name: Node.js Package

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          cache-dependency-path: './sample-packages/npm/package-lock.json'
      - name: Run NPM operations
        working-directory: './sample-packages/npm'
        run: | 
          npm install
          npm ci
          npm test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          cache-dependency-path: './sample-packages/npm/package-lock.json'
      - name: Run NPM operations
        working-directory: './sample-packages/npm'
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: | 
          npm install
          npm ci
          npm publish
