name: Node.js Package

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          cache-dependency-path: './sample-packages/npm/package-lock.json'
      - run: npm ci
        working-directory: './sample-packages/npm'
      - run: npm test
        working-directory: './sample-packages/npm'

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          cache-dependency-path: './sample-packages/npm/package-lock.json'
      - run: npm ci
        working-directory: './sample-packages/npm'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        working-directory: './sample-packages/npm'
